add_newline = true
format = """
$username\
$container\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 30_000

[git_commit]
tag_disabled = false

[git_metrics]
disabled = false

[git_status]
deleted = '-'

[status]
disabled = false
symbol = "x "

[container]
format = '[\[$name\]]($style) '
