[env]
MISE_CARGO_HOME = "{{ xdg_data_home }}/cargo"
MISE_RUSTUP_HOME = "{{ xdg_data_home }}/rustup"

[tools]
deno = "latest"
java = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"

[settings]
experimental = true
status.missing_tools = "always"
